### ISSUE TITLE
`/validate` endpoint returns 200 even if the provided data doesn't validate

### ISSUE THREAD

**Issue by serge-gaia** [surroundaustralia/bdr-public-issues#2]
Before the `/validate` was returning 400 (bad request) for invalid data (with errors in the response) and 200 when the the data was valid.
Now it always returns 200 for good or bad data.

Is it a oversight or is it intentional? 

I prefer to have the status code indicating an error or not.

**Comment by nicholascar** [comment]
Intentional: rereading the HTTP status codes I read that any message that is correctly requested and responded to should return with a 200, even if the message is "your data is invalid". The response contains the details about whether the data is valid or not so the status code is only to indicate if the message wasn't able to be processed or responded to etc.

**Comment by serge-gaia** [comment]
Fair point
